import articleImage1 from 'assets/tempImage1.jpg';

// 기사 리스트
export const articles = [
  { news_id: 1, media: '동아일보', 
    title: '영하 3도  입동 추위 절정 찍었다…내일 추위 풀려도 일교차 여전', 
    content: '어쩌구 저쩌구 왕왕', 
    probability: 100, 
    url: articleImage1 },
  { news_id: 2, media: '동아일보', 
    title: '영하 3도  입동 추위 절정 찍었다…내일 추위 풀려도 일교차 여전', 
    content: '어쩌구 저쩌구 왕왕', 
    probability: 76, 
    url: articleImage1 },
  { news_id: 3, media: '동아일보', 
    title: '영하 3도  입동 추위 절정 찍었다…내일 추위 풀려도 일교차 여전', 
    content: '어쩌구 저쩌구 왕왕', 
    probability: 76, 
    url: articleImage1 },
  { news_id: 4, media: '동아일보', 
    title: '영하 3도  입동 추위 절정 찍었다…내일 추위 풀려도 일교차 여전', 
    content: '어쩌구 저쩌구 왕왕', 
    probability: 40, 
    url: articleImage1 },
  { news_id: 5, media: '동아일보', 
    title: '영하 3도  입동 추위 절정 찍었다…내일 추위 풀려도 일교차 여전', 
    content: '어쩌구 저쩌구 왕왕', 
    probability: 10, 
    url: articleImage1 },
  { news_id: 6, media: '동아일보', 
    title: '영하 3도  입동 추위 절정 찍었다…내일 추위 풀려도 일교차 여전', 
    content: '어쩌구 저쩌구 왕왕', 
    probability: 76, 
    url: articleImage1 },
  { news_id: 7, media: '동아일보', 
    title: '영하 3도  입동 추위 절정 찍었다…내일 추위 풀려도 일교차 여전', 
    content: '어쩌구 저쩌구 왕왕', 
    probability: 76, 
    url: articleImage1 }
]; 